// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/longhoang0304/fiscaris-phnx-api/internal/apps/fiscaris"
)

// Injectors from wire.go:

func InitFiscarisApp() (*fiscaris.FiscarisApp, error) {
	v := fiscaris.NewRoutes()
	handler, err := fiscaris.NewRouter(v)
	if err != nil {
		return nil, err
	}
	httpServer, err := fiscaris.NewHttpServer(handler)
	if err != nil {
		return nil, err
	}
	fiscarisApp := fiscaris.NewFiscarisApp(httpServer)
	return fiscarisApp, nil
}
